# Generated by Django 4.2.2 on 2023-07-02 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_confirmationcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='department',
        ),
    ]
