# Generated by Django 4.2.2 on 2023-07-05 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagefavorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
