# Generated by Django 4.2.2 on 2023-07-04 23:46

from django.db import migrations, models
import django.db.models.deletion
import phone_cases.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaseType',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to=phone_cases.models.case_type_icon_img_path)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rate', models.IntegerField(default=0)),
                ('valid_until', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBrand',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneBrandReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.phonebrand')),
            ],
        ),
        migrations.CreateModel(
            name='CaseTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=phone_cases.models.case_type_img_path)),
                ('order_priority', models.IntegerField(default=0)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.casetype')),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('case_scaffold_img_path', models.ImageField(upload_to=phone_cases.models.phone_case_scaffold_img_path)),
                ('inventory_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('OUT_OF_STOCK', 'Out of stock')], max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('case_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.casetype')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.discount')),
                ('phone_brand_ref', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.phonebrandreference')),
            ],
            options={
                'unique_together': {('phone_brand_ref', 'case_type')},
            },
        ),
    ]
