# Generated by Django 4.2.2 on 2023-07-04 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone_cases', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='phonebrandreference',
            unique_together={('name', 'brand')},
        ),
    ]
