# Generated by Django 4.2.2 on 2023-07-05 20:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0003_alter_imagefavorite_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0004_address_is_active'),
        ('phone_cases', '0002_alter_phonebrandreference_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('discount_rate', models.IntegerField(default=0)),
                ('is_free_shipping', models.BooleanField(default=False)),
                ('max_uses', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField()),
                ('for_all_phone_cases', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('phone_cases', models.ManyToManyField(blank=True, to='phone_cases.phonecase')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.address')),
                ('coupons', models.ManyToManyField(blank=True, to='orders.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('CREATED', 'Created'), ('CANCELED', 'Canceled'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('DISPATCHED', 'Dispatched'), ('RECEIVED', 'Received')], max_length=50)),
                ('details', models.CharField(blank=True, max_length=500)),
                ('set_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderPhoneCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('price', models.FloatField()),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.discount')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='images.image')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order')),
                ('phone_case', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.phonecase')),
            ],
        ),
    ]
