# Generated by Django 4.2.2 on 2023-07-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='id',
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
