# Generated by Django 4.2.2 on 2023-07-07 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('phone_cases', '0001_initial'),
        ('orders', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatushistory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderphonecase',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.discount'),
        ),
        migrations.AddField(
            model_name='orderphonecase',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='images.image'),
        ),
        migrations.AddField(
            model_name='orderphonecase',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderphonecase',
            name='phone_case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='phone_cases.phonecase'),
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.address'),
        ),
        migrations.AddField(
            model_name='order',
            name='coupons',
            field=models.ManyToManyField(blank=True, to='orders.coupon'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='coupon',
            name='phone_cases',
            field=models.ManyToManyField(blank=True, to='phone_cases.phonecase'),
        ),
    ]
