# Generated by Django 4.2.2 on 2023-07-07 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_coupon_id_alter_coupon_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='uses',
            field=models.IntegerField(default=0),
        ),
    ]
